#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service defaults 20-gitlab

PROCESS_NAME="sidekiq"
check_container_initialized
check_service_initialized 30-gitaly

while [ ! -S "${GITLAB_INSTALL_DIR}"/tmp/sockets/private/gitaly.socket ]
do
  sleep 3
done

liftoff

print_info "Starting Sidekiq"
HOME=${GITLAB_HOME}

cd "${GITLAB_INSTALL_DIR}"
silent exec sudo -HEu git bundle exec sidekiq -c {{SIDEKIQ_CONCURRENCY}} -C "${GITLAB_INSTALL_DIR}"/config/sidekiq_queues.yml -e "${RAILS_ENV}" -t "${SIDEKIQ_SHUTDOWN_TIMEOUT}" -P "${GITLAB_INSTALL_DIR}"/tmp/pids/sidekiq.pid -L "${GITLAB_INSTALL_DIR}"/log/sidekiq.log
