#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/11-unicorn ]
do
  sleep 1
done

## Set Debug Mode
  if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ];  then
    set -x
  fi

while [ ! -S ${GITLAB_INSTALL_DIR}/tmp/sockets/gitlab.socket ]
do
  sleep 3
done

if [ ! -f /tmp/state/12-gitaly ]; then
    
    mkdir -p /tmp/state/
	echo 'Initialization Complete' >/tmp/state/12-gitaly
fi

echo ''
echo '** [gitaly] Starting Gitaly'
HOME=${GITLAB_HOME}
set -e

cd ${GITLAB_INSTALL_DIR}
exec s6-setuidgid git gitaly ${GITLAB_GITALY_INSTALL_DIR}/config.toml  > ${GITLAB_INSTALL_DIR}/log/gitaly.log
