#!/usr/bin/with-contenv bash

## Set Debug Mode
  if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ];  then
    set -x
  fi

  ### Adjust NGINX Runtime Variables
  UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE:="2G"}
  sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /etc/nginx/nginx.conf
  
  mkdir -p /var/log/gitlab/nginx
  chown -R git /var/log/gitlab/nginx
  mkdir -p /tmp/nginx
  chown -R git /tmp/nginx

  mkdir -p /tmp/state
  touch /tmp/state/09-nginx
