#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/10-gitlab-init ]
do
  sleep 1
done

## Set Debug Mode
  if [ "$DEBUG_MODE" = "TRUE" ] || [ "$DEBUG_MODE" = "true" ];  then
    set -x
  fi

if [ ! -f /tmp/state/11-unicorn ]; then
    mkdir -p /tmp/state/
	echo 'Initialization Complete' >/tmp/state/11-unicorn
fi

echo ''
echo '** [unicorn] Starting Unicorn'
HOME=${GITLAB_HOME}

cd ${GITLAB_INSTALL_DIR}
exec s6-setuidgid git bundle exec unicorn_rails -c ${GITLAB_INSTALL_DIR}/config/unicorn.rb -E ${RAILS_ENV}

