#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service defaults 20-gitlab

PROCESS_NAME="workhorse"
check_container_initialized
check_service_initialized 40-sidekiq
liftoff

print_start "Starting Gitlab Workhorse"
HOME=${GITLAB_HOME}
silent exec sudo -HEu git /usr/local/bin/gitlab-workhorse -listenUmask 0 -listenNetwork tcp -listenAddr ":8181" -authBackend http://127.0.0.1:8080{{GITLAB_RELATIVE_URL_ROOT}} -authSocket "${GITLAB_INSTALL_DIR}"/tmp/sockets/gitlab.socket -documentRoot "${GITLAB_INSTALL_DIR}"/public -proxyHeadersTimeout {{GITLAB_WORKHORSE_TIMEOUT}} -secretPath "${GITLAB_INSTALL_DIR}/.gitlab_workhorse_secret"