#!/usr/bin/with-contenv bash

source /assets/functions/00-container
prepare_service defaults 20-gitlab

PROCESS_NAME="mailroom"
check_container_initialized
check_service_initialized 50-workhorse
liftoff

print_start "Starting Mailroom"
HOME=${GITLAB_HOME}

cd "${GITLAB_INSTALL_DIR}"
silent sudo -HEu git bundle exec mail_room -c ${GITLAB_INSTALL_DIR}/config/mail_room.yml
