#!/usr/bin/with-contenv bash
source /assets/functions/00-container
prepare_service defaults 20-gitlab

PROCESS_NAME="ssh"
check_container_initialized
liftoff
set -x
print_start "Starting sshd"
silent exec s6-setuidgid git /usr/sbin/sshd -d -D
