#!/usr/bin/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="puma"

check_container_initialized
check_service_initialized init 20-gitlab
liftoff

print_info "Starting Puma"
HOME=${GITLAB_HOME}
cd ${GITLAB_INSTALL_DIR}
silent exec s6-setuidgid git bundle exec puma --config ${GITLAB_INSTALL_DIR}/config/puma.rb --environment ${RAILS_ENV}
